### ISSUE TITLE
Client library

### ISSUE THREAD

**Issue by vbalien** [ynifamily3/CommentsApi#2]
A client-side library written in a language such as Javascript is required for ease of use.

**Comment by ynifamily3** [comment]
만들 예정입니다. 감사합니다. 혁신적인 모습으로 언제나 웹마스터님들을 모시겠습니다 ^^*
I am going to make it. Thank you. We will always serve webmasters with an innovative look :D
作成する予定です。ありがとうございます。革新的な姿でいつものウェブマスター様をお迎えいたします (^^)

**Comment by ynifamily3** [comment]
https://github.com/ynifamily3/CommentsFront
